In [1]:
import pandas as pd
import numpy as np

In [2]:
data_protein = pd.read_csv('resultado/00_prepro_protein.groups.tsv', sep='\t', index_col=0)

In [3]:

main_columns = ['CBB_01', 'CBB_02', 'CBB_03','rGlyP_07', 'rGlyP_08','rGlyP_09',]
num_columns = ['CBB_UP_01', 'CBB_UP_02', 'CBB_UP_03', 'rGlyP_UP_07', 'rGlyP_UP_08', 'rGlyP_UP_09']
all_columns = main_columns + num_columns
cepa_CBB = ['CBB_01', 'CBB_02', 'CBB_03']
cepa_rGlyP = ['rGlyP_07', 'rGlyP_08','rGlyP_09']

In [4]:
data_protein

,CBB_01,CBB_02,CBB_03,rGlyP_07,rGlyP_08,rGlyP_09,CBB_UP_01,CBB_UP_02,CBB_UP_03,rGlyP_UP_07,rGlyP_UP_08,rGlyP_UP_09
Protein.Group,,,,,,,,,,,,
O07451,26.392931,26.320032,26.349343,NaN,21.201639,NaN,29,34,33,0,4,0
O30338,21.483608,21.568191,21.640735,21.467156,21.488334,21.483205,3,3,3,3,3,3
O34162,21.469868,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0
O87816,27.211578,27.108774,27.220774,27.499516,27.533413,27.568671,12,9,12,12,14,12
P14611,32.618989,32.412991,32.299652,32.993430,32.812984,32.921867,68,66,69,68,69,69
...,...,...,...,...,...,...,...,...,...,...,...,...
Q8KLU8,22.928322,22.878103,22.630112,23.168801,23.044661,23.121074,5,5,5,5,6,5
Q9K4U8,21.286884,21.189563,20.882880,NaN,NaN,21.081498,1,1,1,0,0,1
Q9K4V0,21.383415,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0
Q9X6U2,29.171160,29.063804,28.921111,29.645631,29.482916,29.616149,21,22,22,22,22,21
Q9ZHI5,30.702322,30.292324,30.113533,30.430950,30.034561,30.213630,17,16,16,16,16,15

In [5]:
data_protein[cepa_CBB]

                  CBB_01     CBB_02     CBB_03
Protein.Group
O07451         26.392931  26.320032  26.349343
O30338         21.483608  21.568191  21.640735
O34162         21.469868        NaN        NaN
O87816         27.211578  27.108774  27.220774
P14611         32.618989  32.412991  32.299652
...                  ...        ...        ...
Q8KLU8         22.928322  22.878103  22.630112
Q9K4U8         21.286884  21.189563  20.882880
Q9K4V0         21.383415        NaN        NaN
Q9X6U2         29.171160  29.063804  28.921111
Q9ZHI5         30.702322  30.292324  30.113533

[3691 rows x 3 columns]

In [6]:
data_protein['total_no_na_CBB'] = data_protein[cepa_CBB].count(axis=1)

In [7]:
data_protein

,CBB_01,CBB_02,CBB_03,rGlyP_07,rGlyP_08,rGlyP_09,CBB_UP_01,CBB_UP_02,CBB_UP_03,rGlyP_UP_07,rGlyP_UP_08,rGlyP_UP_09,total_no_na_CBB
Protein.Group,,,,,,,,,,,,,
O07451,26.392931,26.320032,26.349343,NaN,21.201639,NaN,29,34,33,0,4,0,3
O30338,21.483608,21.568191,21.640735,21.467156,21.488334,21.483205,3,3,3,3,3,3,3
O34162,21.469868,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0,1
O87816,27.211578,27.108774,27.220774,27.499516,27.533413,27.568671,12,9,12,12,14,12,3
P14611,32.618989,32.412991,32.299652,32.993430,32.812984,32.921867,68,66,69,68,69,69,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Q8KLU8,22.928322,22.878103,22.630112,23.168801,23.044661,23.121074,5,5,5,5,6,5,3
Q9K4U8,21.286884,21.189563,20.882880,NaN,NaN,21.081498,1,1,1,0,0,1,3
Q9K4V0,21.383415,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0,1
Q9X6U2,29.171160,29.063804,28.921111,29.645631,29.482916,29.616149,21,22,22,22,22,21,3
Q9ZHI5,30.702322,30.292324,30.113533,30.430950,30.034561,30.213630,17,16,16,16,16,15,3

In [8]:
data_protein['total_no_na_rGlyP'] = data_protein[cepa_rGlyP].count(axis=1)

In [9]:
data_protein

,CBB_01,CBB_02,CBB_03,rGlyP_07,rGlyP_08,rGlyP_09,CBB_UP_01,CBB_UP_02,CBB_UP_03,rGlyP_UP_07,rGlyP_UP_08,rGlyP_UP_09,total_no_na_CBB,total_no_na_rGlyP
Protein.Group,,,,,,,,,,,,,,
O07451,26.392931,26.320032,26.349343,NaN,21.201639,NaN,29,34,33,0,4,0,3,1
O30338,21.483608,21.568191,21.640735,21.467156,21.488334,21.483205,3,3,3,3,3,3,3,3
O34162,21.469868,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0,1,0
O87816,27.211578,27.108774,27.220774,27.499516,27.533413,27.568671,12,9,12,12,14,12,3,3
P14611,32.618989,32.412991,32.299652,32.993430,32.812984,32.921867,68,66,69,68,69,69,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Q8KLU8,22.928322,22.878103,22.630112,23.168801,23.044661,23.121074,5,5,5,5,6,5,3,3
Q9K4U8,21.286884,21.189563,20.882880,NaN,NaN,21.081498,1,1,1,0,0,1,3,1
Q9K4V0,21.383415,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0,1,0
Q9X6U2,29.171160,29.063804,28.921111,29.645631,29.482916,29.616149,21,22,22,22,22,21,3,3
Q9ZHI5,30.702322,30.292324,30.113533,30.430950,30.034561,30.213630,17,16,16,16,16,15,3,3

In [10]:
data_protein[['total_no_na_CBB', 'total_no_na_rGlyP']]

               total_no_na_CBB  total_no_na_rGlyP
Protein.Group
O07451                       3                  1
O30338                       3                  3
O34162                       1                  0
O87816                       3                  3
P14611                       3                  3
...                        ...                ...
Q8KLU8                       3                  3
Q9K4U8                       3                  1
Q9K4V0                       1                  0
Q9X6U2                       3                  3
Q9ZHI5                       3                  3

[3691 rows x 2 columns]

Al menos uno de los grupos tiene dos datos como minimo.

In [11]:
data_protein[['total_no_na_CBB', 'total_no_na_rGlyP']] >= 2

               total_no_na_CBB  total_no_na_rGlyP
Protein.Group
O07451                    True              False
O30338                    True               True
O34162                   False              False
O87816                    True               True
P14611                    True               True
...                        ...                ...
Q8KLU8                    True               True
Q9K4U8                    True              False
Q9K4V0                   False              False
Q9X6U2                    True               True
Q9ZHI5                    True               True

[3691 rows x 2 columns]

Verdad o Verdad = Verdad
Verdad o Falso = Verdad
Falso o Verdad = Verdad
Falso o Falso = Falso

In [12]:
filtro = data_protein[['total_no_na_CBB', 'total_no_na_rGlyP']] >= 2

In [13]:
filtro

               total_no_na_CBB  total_no_na_rGlyP
Protein.Group
O07451                    True              False
O30338                    True               True
O34162                   False              False
O87816                    True               True
P14611                    True               True
...                        ...                ...
Q8KLU8                    True               True
Q9K4U8                    True              False
Q9K4V0                   False              False
Q9X6U2                    True               True
Q9ZHI5                    True               True

[3691 rows x 2 columns]

In [14]:
filtro = filtro.any(axis=1)
data_protein[['total_no_na_CBB', 'total_no_na_rGlyP']][filtro]

               total_no_na_CBB  total_no_na_rGlyP
Protein.Group
O07451                       3                  1
O30338                       3                  3
O87816                       3                  3
P14611                       3                  3
P14697                       3                  3
...                        ...                ...
Q83WS0                       0                  3
Q8KLU8                       3                  3
Q9K4U8                       3                  1
Q9X6U2                       3                  3
Q9ZHI5                       3                  3

[3422 rows x 2 columns]

In [15]:
data_protein_filtro = data_protein[all_columns][filtro]

In [16]:
data_protein.shape[0], data_protein_filtro.shape[0]

(3691, 3422)

In [17]:
data_protein_filtro.to_csv('resultado/01_filtro_protein.groups.tsv', sep='\t')