In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(style="whitegrid")

In [2]:
data_protein = pd.read_csv('03_imputados_protein.groups.tsv', sep='\t', index_col=0)

In [3]:
data_protein

,CBB_01,CBB_02,CBB_03,rGlyP_07,rGlyP_08,rGlyP_09,CBB_UP_01,CBB_UP_02,CBB_UP_03,rGlyP_UP_07,rGlyP_UP_08,rGlyP_UP_09,CBB_01_imputado,CBB_02_imputado,CBB_03_imputado,rGlyP_07_imputado,rGlyP_08_imputado,rGlyP_09_imputado
Protein.Group,,,,,,,,,,,,,,,,,,
O07451,26.392931,26.320032,26.349343,21.936549,21.201639,20.454058,29,34,33,0,4,0,No,No,No,Si,No,Si
O30338,21.483608,21.568191,21.640735,21.467156,21.488334,21.483205,3,3,3,3,3,3,No,No,No,No,No,No
O87816,27.211578,27.108774,27.220774,27.499516,27.533413,27.568671,12,9,12,12,14,12,No,No,No,No,No,No
P14611,32.618989,32.412991,32.299652,32.993430,32.812984,32.921867,68,66,69,68,69,69,No,No,No,No,No,No
P14697,27.982094,28.089317,28.277010,28.806529,28.993055,29.002088,40,41,41,43,43,43,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Q7WXU0,26.380829,26.527723,26.582587,24.817430,24.982458,24.917217,8,7,8,7,7,6,No,No,No,No,No,No
Q83WS0,20.912823,20.766801,19.905533,33.212505,33.180884,33.246544,0,0,0,84,83,84,Si,Si,Si,No,No,No
Q8KLU8,22.928322,22.878103,22.630112,23.168801,23.044661,23.121074,5,5,5,5,6,5,No,No,No,No,No,No
Q9X6U2,29.171160,29.063804,28.921111,29.645631,29.482916,29.616149,21,22,22,22,22,21,No,No,No,No,No,No
Q9ZHI5,30.702322,30.292324,30.113533,30.430950,30.034561,30.213630,17,16,16,16,16,15,No,No,No,No,No,No

In [4]:
df_anotaciones = pd.read_csv('Cupriavidus_necator_H16_proteome_annotations_plus_C1.txt', sep='\t', index_col=0)

In [5]:
df_anotaciones

,Entry Name,Protein names,Gene Names,Organism,Length,Gene Ontology (biological process),Gene Ontology (cellular component),Gene Ontology (GO),Gene Ontology (molecular function),Gene Ontology IDs,KEGG
Entry,,,,,,,,,,,
O34162,HEMN_CUPNH,Oxygen-independent coproporphyrinogen III oxid...,hemN H16_A3615,Cupriavidus necator (strain ATCC 17699 / DSM 4...,494,porphyrin-containing compound biosynthetic pro...,cytoplasm [GO:0005737],"cytoplasm [GO:0005737]; 4 iron, 4 sulfur clust...","4 iron, 4 sulfur cluster binding [GO:0051539];...",GO:0004109; GO:0005737; GO:0006779; GO:0006782...,reh:H16_A3615;
P14611,THIL_CUPNH,Acetyl-CoA acetyltransferase (EC 2.3.1.9) (Ace...,phaA phbA H16_A1438,Cupriavidus necator (strain ATCC 17699 / DSM 4...,393,poly-hydroxybutyrate biosynthetic process [GO:...,cytoplasm [GO:0005737],cytoplasm [GO:0005737]; acetyl-CoA C-acetyltra...,acetyl-CoA C-acetyltransferase activity [GO:00...,GO:0003985; GO:0005737; GO:0042619,reh:H16_A1438;
P14697,PHAB_CUPNH,Acetoacetyl-CoA reductase (EC 1.1.1.36),phaB phbB H16_A1439,Cupriavidus necator (strain ATCC 17699 / DSM 4...,246,poly-hydroxybutyrate biosynthetic process [GO:...,cytoplasm [GO:0005737],cytoplasm [GO:0005737]; acetoacetyl-CoA reduct...,acetoacetyl-CoA reductase activity [GO:0018454],GO:0005737; GO:0018454; GO:0042619,reh:H16_A1439;
P31892,MBHS_CUPNH,Uptake hydrogenase small subunit (EC 1.12.99.6...,hoxK PHG001,Cupriavidus necator (strain ATCC 17699 / DSM 4...,360,anaerobic respiration [GO:0009061],[Ni-Fe] hydrogenase complex [GO:0044569]; ferr...,[Ni-Fe] hydrogenase complex [GO:0044569]; ferr...,"3 iron, 4 sulfur cluster binding [GO:0051538];...",GO:0005886; GO:0008901; GO:0009055; GO:0009061...,reh:PHG001;
P39185,NAPA_CUPNH,Periplasmic nitrate reductase (EC 1.9.6.1),napA PHG211,Cupriavidus necator (strain ATCC 17699 / DSM 4...,831,cellular respiration [GO:0045333]; Mo-molybdop...,membrane [GO:0016020]; nitrate reductase compl...,membrane [GO:0016020]; nitrate reductase compl...,"4 iron, 4 sulfur cluster binding [GO:0051539];...",GO:0005506; GO:0006777; GO:0009055; GO:0009325...,reh:PHG211;
...,...,...,...,...,...,...,...,...,...,...,...
Q7WXT7,Q7WXT7_CUPNH,Putative transposase,PHG029,Cupriavidus necator (strain ATCC 17699 / DSM 4...,109,NaN,NaN,NaN,NaN,NaN,reh:PHG029;
Q7WXT8,Q7WXT8_CUPNH,Putative TonB-dependent outer membrane receptor,PHG028,Cupriavidus necator (strain ATCC 17699 / DSM 4...,738,NaN,cell outer membrane [GO:0009279],cell outer membrane [GO:0009279]; siderophore ...,siderophore uptake transmembrane transporter a...,GO:0009279; GO:0015344,reh:PHG028;
P55818,MTDA_METEA,Bifunctional protein MdtA [Includes: NADP-depe...,mtdA MexAM1_META1p1728,Methylorubrum extorquens (strain ATCC 14718 / ...,288,formaldehyde catabolic process [GO:0046294]; o...,cytoplasm [GO:0005737],cytoplasm [GO:0005737]; methylenetetrahydrofol...,methylenetetrahydrofolate dehydrogenase (NADP+...,GO:0004488; GO:0005737; GO:0006730; GO:0046294,mea:Mex_1p1728;
Q83WS0,FTHS_METEA,Formate--tetrahydrofolate ligase (EC 6.3.4.3) ...,fhs ftfL MexAM1_META1p0329,Methylorubrum extorquens (strain ATCC 14718 / ...,557,tetrahydrofolate interconversion [GO:0035999],NaN,ATP binding [GO:0005524]; formate-tetrahydrofo...,ATP binding [GO:0005524]; formate-tetrahydrofo...,GO:0004329; GO:0005524; GO:0035999,mea:Mex_1p0329;
Q49135,FCHA_METEA,Methenyltetrahydrofolate cyclohydrolase (EC 3....,fchA MexAM1_META1p1729,Methylorubrum extorquens (strain ATCC 14718 / ...,208,one-carbon metabolic process [GO:0006730],membrane [GO:0016020],membrane [GO:0016020]; methenyltetrahydrofolat...,methenyltetrahydrofolate cyclohydrolase activi...,GO:0004477; GO:0006730; GO:0016020,mea:Mex_1p1729;

In [6]:
df_final = pd.merge(
    data_protein, 
    df_anotaciones, 
    left_index=True,    # Usa el índice de data_protein
    right_on='Entry',   # Usa la columna 'Entry' de df_anotaciones
)

In [7]:
df_final.columns

Index(['CBB_01', 'CBB_02', 'CBB_03', 'rGlyP_07', 'rGlyP_08', 'rGlyP_09',
       'CBB_UP_01', 'CBB_UP_02', 'CBB_UP_03', 'rGlyP_UP_07', 'rGlyP_UP_08',
       'rGlyP_UP_09', 'CBB_01_imputado', 'CBB_02_imputado', 'CBB_03_imputado',
       'rGlyP_07_imputado', 'rGlyP_08_imputado', 'rGlyP_09_imputado',
       'Entry Name', 'Protein names', 'Gene Names', 'Organism', 'Length',
       'Gene Ontology (biological process)',
       'Gene Ontology (cellular component)', 'Gene Ontology (GO)',
       'Gene Ontology (molecular function)', 'Gene Ontology IDs', 'KEGG'],
      dtype='object')

In [8]:
df_final['Organism'].value_counts()

Organism
Cupriavidus necator (strain ATCC 17699 / DSM 428 / KCTC 22496 / NCIMB 10442 / H16 / Stanier 337) (Ralstonia eutropha)    2916
Methylorubrum extorquens (strain ATCC 14718 / DSM 1338 / JCM 2805 / NCIMB 9133 / AM1) (Methylobacterium extorquens)         3
Name: count, dtype: int64

In [9]:
df_final['Gene Ontology (GO)'].value_counts()

Gene Ontology (GO)
hydrolase activity [GO:0016787]                                                                                                                                                                                                                                                                                                                                           38
membrane [GO:0016020]                                                                                                                                                                                                                                                                                                                                                     35
oxidoreductase activity [GO:0016491]                                                                                                                                                                                                                                                                                                                                      33
DNA binding [GO:0003677]; DNA-binding transcription factor activity [GO:0003700]; negative regulation of DNA-templated transcription [GO:0045892]                                                                                                                                                                                                                         26
DNA binding [GO:0003677]; DNA-binding transcription factor activity [GO:0003700]                                                                                                                                                                                                                                                                                          24
                                                                                                                                                                                                                                                                                                                                                                          ..
ribonucleoside-diphosphate reductase complex [GO:0005971]; ATP binding [GO:0005524]; ribonucleoside-diphosphate reductase activity, thioredoxin disulfide as acceptor [GO:0004748]; deoxyribonucleotide biosynthetic process [GO:0009263]                                                                                                                                  1
cytoplasm [GO:0005737]; N-acetylmuramoyl-L-alanine amidase activity [GO:0008745]; cell wall organization [GO:0071555]; peptidoglycan catabolic process [GO:0009253]; peptidoglycan turnover [GO:0009254]                                                                                                                                                                   1
signal recognition particle [GO:0048500]; 7S RNA binding [GO:0008312]; ATP hydrolysis activity [GO:0016887]; GTP binding [GO:0005525]; GTPase activity [GO:0003924]; SRP-dependent cotranslational protein targeting to membrane [GO:0006614]                                                                                                                              1
cytosol [GO:0005829]; membrane [GO:0016020]; guanine phosphoribosyltransferase activity [GO:0052657]; hypoxanthine phosphoribosyltransferase activity [GO:0004422]; magnesium ion binding [GO:0000287]; nucleotide binding [GO:0000166]; GMP salvage [GO:0032263]; guanine salvage [GO:0006178]; hypoxanthine metabolic process [GO:0046100]; IMP salvage [GO:0032264]     1
cytosol [GO:0005829]; aspartate 1-decarboxylase activity [GO:0004068]; alanine biosynthetic process [GO:0006523]; pantothenate biosynthetic process [GO:0015940]                                                                                                                                                                                                           1
Name: count, Length: 1643, dtype: int64

In [10]:
df_final['KEGG'] = df_final['KEGG'].apply(lambda x: x.replace(';', ''))

In [11]:
df_final.to_csv('04_annotados_protein.groups.tsv', sep='\t')